server:
  port: ${PORT:8091}

vaadin:
  allowed-packages: io.sapl

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: sapl-api-webapp
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://keycloak.sapl.local:30080/realms/businessA
